services:
  - type: web
    name: instagram-meta-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webhook:app
    envVars:
      - key: VERIFY_TOKEN
        value: POSTBOT123
