services:
  - type: web
    name: thinkfinex-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: VERIFY_TOKEN
        value: production
